name: Code checks and merge to the master branch

on:
  push:
    branches:
      - '**'
      - '!master'

# noinspection YAMLSchemaValidation
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint (pass score = 9/10)
      run: |
        pylint $(git ls-files '*.py')
    - name: Create PR Release to main
      run: gh pr create --title "Auto PR from github action" --body "Static code analysis (pylint > 9/10) has completed"
      env:
        GH_TOKEN: ${{ secrets.ACTIONSECRET }}